# example of a machine specific settings
windows:
  mainwindow:
    kwargs:
      confirm_exit: false

data_plugins:
  tooltable:
    provider: qtpyvcp.plugins.tool_table:ToolTable
    kwargs:
        columns: TXYZDR

settings:

  # VTK backplot view settings

  backplot.show-grid:
    default_value: false

  backplot.show-program-bounds:
    default_value: false

  backplot.show-program-labels:
    default_value: false

  backplot.show-program-ticks:
    default_value: false

  backplot.show-machine-bounds:
    default_value: true

  backplot.show-machine-labels:
    default_value: false

  backplot.show-machine-ticks:
    default_value: false

  backplot.perspective-view:
    default_value: false

  backplot.view:
    default_value: P
    options: ["X: Front View", "XZ: Lathe View", "XZ2: Lathe View", "Y: Front View", "Z: Top View", "Z2: Bottom View", "P: Isometric"]

  backplot.multitool-colors:
    default_value: True

