language: python
install:
- pip install mkdocs
- pip install mkdocs-material
script:
- mkdocs build --verbose --clean --strict
deploy:
 provider: pages
 skip_cleanup: true
 keep-history: false
 github_token: $GH_TOKEN
 local_dir: site
 on:
   branch: master

# notifications:
#   irc:
#     channels:
#       - "chat.freenode.net#hazzy"
#     template:
#       - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
#       - "Diff view : %{compare_url}"
#       - "Build details : %{build_url}"
#
#   webhooks:
#     urls:
#       - https://webhooks.gitter.im/e/f52c254eacf15cb158b5
#     on_success: always
#     on_failure: always
#     on_start: never
