{% include "default_menubar.yml" %}

vcp:
  name: Not Set
  version: Not Set
  author: Not Set
  description: No description provided.

windows:
  mainwindow:
    provider: qtpyvcp.widgets.form_widgets.main_window:VCPMainWindow

# This sections defines the default Data Sources
data_plugins:
  status:
    provider: qtpyvcp.plugins.status:Status
    kwargs:
      cycle_time: 75

  persistent_data_manager:
    provider: qtpyvcp.plugins.persistent_data_manager:PersistentDataManager
    kwargs:
      # serialization method to use: json or pickle
      serialization_method: pickle
      # persistence_file: .vcp_data.json

  settings:
    provider: qtpyvcp.plugins.settings:Settings

  position:
    provider: qtpyvcp.plugins.positions:Position
    kwargs:
      report_actual_pos: True
      use_program_units: True

  tooltable:
    provider: qtpyvcp.plugins.tool_table:ToolTable

  offsettable:
    provider: qtpyvcp.plugins.offset_table:OffsetTable

  notifications:
    provider: qtpyvcp.plugins.notifications:Notifications
    kwargs:
      # show notification popups
      enabled: True
      # "native" or "dbus"
      mode: native
      # max number of notifications to show
      max_messages: 5
      # whether to save messages on exit
      persistent: True

  file_locations:
    provider: qtpyvcp.plugins.file_locations:FileLocations
    log_level: debug
    kwargs:
      default_location: NC Files
      local_locations:
        # format: Location Name: path
        Home: ~/
        Desktop: ~/Desktop
        NC Files: ~/linuxcnc/nc_files
      network_locations:

    exportedhal:
        provider: qtpyvcp.plugins.exported_hal:ExportedHal

  virtual_input:
    provider: qtpyvcp.plugins.virtual_input_manager:VirtualInputManager

dialogs:
  open_file:
    provider: qtpyvcp.widgets.dialogs.open_file_dialog:OpenFileDialog

  set_work_offsets:
    provider: qtpyvcp.widgets.dialogs.offsets_dialog:OffsetsDialog

  tool_edit:
    provider: qtpyvcp.widgets.dialogs.tool_edit_dialog:ToolEditDialog

  probe_sim:
    provider: qtpyvcp.widgets.dialogs.probesim_dialog:ProbeSim

  about_qtpyvcp:
    provider: qtpyvcp.widgets.dialogs.about_dialog:AboutDialog

virtual_input_providers:
  number:
    provider: qtpyvcp.widgets.virtual_input.virtual_input:VirtualInput
    kwargs:
      ui_file: {{ file.dir }}/../widgets/virtual_input/numpad.ui

#  number.int:
#    provider: qtpyvcp.widgets.virtual_input.virtual_input:VirtualInput
#    kwargs:
#      ui_file: {{ file.dir }}/../widgets/virtual_input/numpad.ui
#
#  number.float:
#    provider: qtpyvcp.widgets.virtual_input.virtual_input:VirtualInput
#    kwargs:
#      ui_file: {{ file.dir }}/../widgets/virtual_input/numpad.ui

  text:
    provider: qtpyvcp.widgets.virtual_input.virtual_input:VirtualInput
    kwargs:
      ui_file: {{ file.dir }}/../widgets/virtual_input/keyboard.ui

#  text.gcode:
#    provider: qtpyvcp.widgets.virtual_input.virtual_input:VirtualInput
#    kwargs:
#      ui_file: {{ file.dir }}/../widgets/virtual_input/keyboard.ui

application:
  provider: qtpyvcp.app.application:VCPApplication
  kwargs:
#    stylesheet: {{ file.dir }}/widgets/default_stylesheet.qss   # application wide stylesheet

settings:
  touch-probe.diameter-offset:
    default_value: .123123
    persistent: true
    min_value: 0
    max_value: 1

  dro.display-units:
    default_value: 0
    options: [Auto, Inch, Metric]

  dro.lathe-radius-mode:
    default_value: 0
    options: [Auto, Radius, Diameter]

  dro.inch-format:
    default_value: '%9.4f'
    value_type: str

  dro.millimeter-format:
    default_value: '%9.3f'
    value_type: str

  dro.degree-format:
    default_value: '%9.2f'

  # VTK backplot view settings

  backplot.show-grid:
    default_value: false

  backplot.show-program-bounds:
    default_value: false

  backplot.show-program-labels:
    default_value: false

  backplot.show-program-ticks:
    default_value: false

  backplot.show-machine-bounds:
    default_value: false

  backplot.show-machine-labels:
    default_value: false

  backplot.show-machine-ticks:
    default_value: false

  backplot.perspective-view:
    default_value: True

  backplot.view:
    default_value: 0
    options: ["X: Front View", "XZ: Lathe View", "XZ2: Lathe View", "Y: Front View", "Z: Top View", "Z2: Bottom View", "P: Isometric"]

  backplot.multitool-colors:
    default_value: True

  # Tool Table Column settings

  tool_table.column_x:
    default_value: false

  tool_table.column_y:
    default_value: false

  tool_table.column_z:
    default_value: false

  tool_table.column_a:
    default_value: false

  tool_table.column_b:
    default_value: false

  tool_table.column_c:
    default_value: false

  tool_table.column_u:
    default_value: false

  tool_table.column_v:
    default_value: false

  tool_table.column_w:
    default_value: false

  tool_table.column_p:
    default_value: false

  tool_table.column_q:
    default_value: false

  tool_table.column_t:
    default_value: false

  tool_table.column_r:
    default_value: false

  tool_table.column_d:
    default_value: false

