{% include "default_menubar.yml" %}

vcp:
  name: Not Set
  version: Not Set
  author: Not Set
  description: No description provided.

windows:
  mainwindow:
    provider: qtpyvcp.widgets.form_widgets.main_window:VCPMainWindow

# This sections defines the default Data Sources
data_plugins:
  status:
    provider: qtpyvcp.plugins.status:Status
    kwargs:
      cycle_time: 75

  persistent_data_manager:
    provider: qtpyvcp.plugins.persistent_data_manager:PersistentDataManager
    kwargs:
      # serialization method to use: json or pickle
      serialization_method: json
      # persistence_file: .vcp_data.json

  settings:
    provider: qtpyvcp.plugins.settings:Settings

  position:
    provider: qtpyvcp.plugins.positions:Position
    kwargs:
      report_actual_pos: True
      use_program_units: True

  tooltable:
    provider: qtpyvcp.plugins.tool_table:ToolTable

  offsettable:
    provider: qtpyvcp.plugins.offset_table:OffsetTable

  notifications:
    provider: qtpyvcp.plugins.notifications:Notifications
    kwargs:
      # show notification popups
      enabled: True
      # "native" or "dbus"
      mode: native
      # max number of notifications to show
      max_messages: 5
      # whether to save messages on exit
      persistent: True

  file_locations:
    provider: qtpyvcp.plugins.file_locations:FileLocations
    kwargs:
      default_location: NC Files
      local_locations:
        # format: Location Name: path
        Home: ~/
        Desktop: ~/Desktop
        NC Files: ~/linuxcnc/nc_files
      network_locations:

dialogs:
  open_file:
    provider: qtpyvcp.widgets.dialogs.open_file_dialog:OpenFileDialog

  set_work_offsets:
    provider: qtpyvcp.widgets.dialogs.offsets_dialog:OffsetsDialog

  tool_edit:
    provider: qtpyvcp.widgets.dialogs.base_dialog:BaseDialog
    kwargs:
      ui_file: {{ file.dir }}/../widgets/dialogs/tooledit_dialog.ui

  probe_sim:
    provider: qtpyvcp.widgets.dialogs.probesim_dialog:ProbeSim

  about_qtpyvcp:
    provider: qtpyvcp.widgets.dialogs.about_dialog:AboutDialog

virtual_keyboards:
  engine:
    provider: qtpyvcp.widgets.virtual_keyboards.vkb_engine:VKBEngine
    kwargs:
      enabled: True

  default:
    provider: qtpyvcp.widgets.virtual_keyboards.vkb_base:VKBBase
    kwargs:
      ui_file: {{ file.dir }}/../widgets/virtual_keyboards/full_keyboard.ui
#      modal: False
#      overrides:
#        esc:
  mdi:
    provider: qtpyvcp.widgets.virtual_keyboards.vkb_base:VKBBase
    kwargs:
      ui_file: {{ file.dir }}/../widgets/virtual_keyboards/mdi_keyboard.ui
#      frameless: True
#      modal: False
#      overrides:
#        esc:

  int:
    provider: qtpyvcp.widgets.virtual_keyboards.vkb_base:VKBBase
    kwargs:
      ui_file: {{ file.dir }}/../widgets/virtual_keyboards/int_entry.ui
#      frameless: True
#      modal: False
#      overrides:
#        esc:

application:
  provider: qtpyvcp.app.application:VCPApplication
  kwargs:
#    stylesheet: {{ file.dir }}/widgets/default_stylesheet.qss   # application wide stylesheet

settings:
  touch-probe.diameter-offset:
    default_value: 0.0
    persistent: true
    min_value: 0
    max_value: 1

  virtual-keyboard.enable:
    default_value: true
    persistent: true
